version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    env_file:
      - python3-virtualenv/pyvenv.cfg
    volumes:
      - ./flask.sqlite:/myportfolio/flask.sqlite