version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    env_file:
      - info.env
    volumes:
      - ./flask.sqlite:/myportfolio/flask.sqlite

  db:
    image: postgres
    restart: always
    